---
title: "Academica and Educator focussed writing"
output: html_document
---

# Abstract

Peptides are an important analyte for proteomics, and calculating their mass, charge, and mass/charge ratio is crucial for experimental design and data interpretation. While there are multiple online tools for calculating these attributes for a given peptide, they are generally 'black boxes' and require no understanding of the acid/base chemistry or the chemical structure of the peptide. They also are not generally customizable, and are not made for automated analysis or handling many individual peptides at once. By using R, we will write functions from scratch to do these calculations on peptides, and connect the dots from chemistry, to math, to code, to scientific conclusion. As coding becomes more integrated into every type of scientific laboratory, it is essential to include in curriculum examples of the powerful ways that programming can be applied to basic chemistry principles to streamline data analysis.

# Project Overview

There are four distinct levels of comfort that one can have with applying code to data. The lowest level is simply to take a script or function that is designed to perform some action (plotting a graph, calculating a pH, etc) and use it to perform that action on an example dataset while following step by step instructions. The second level is to take a script or function and use it on your own original data that hasn't been analyzed before. The next level would be to take the script or function, and make modifications that tweak what the purpose of the code is. This could be a minor tweak or a major tweak; for example, changing the output of the data from a table to a plot, or taking a pattern matching algorithm designed for DNA sequences and making it work with protein sequences as well. The final level is to write your own code from scratch. The project outlined here will go through all four of these levels, and depending on the experience level of the audience, these different steps can be combined in any number of ways. No matter what level the students are working with, the exposure to programming, and the application of code to scientific questions is a necessary experience to have.

As described in the background section, the scientific question at hand is to calculate charge, mass, and mass/charge ratio for peptides. We will focus on calculating charge for the first several steps, and then move on to mass and mass/charge for more challenging assignments. The first step, (simply implementing code while following instructions) deals with calculating the charge on a peptide. [An excellent article by Dr. Paul A. Sims](https://pubs.acs.org/doi/abs/10.1021/ed100232j) outlines the theory behind this calculation, and the equations that are needed. The second step involves applying this charge calculation to a real world example, Ion Exchange Chromatography, and has the students predict the order that peptides will elute from a column. The third step is divided into two parts, a and b. In 'a', students will modify a `for` loop to obtain charge values for a long list of peptides. In part 'b', a function to calculate mass and mass/charge ratio is given, and students must edit these to create a function that predicts m/z for a peptide in MALDI. Finally, the forth step sets forward several questions related to peptide charge and mass for the student to answer using their own ideas and original code.

# Paragraph from the background section
Learning how to use code as a tool for scientific research often seems like a daunting task. There are many publications that include a phrase along the lines of, "The fasta files were digested *in silico* and probability scores were assigned using an in-house python script". For many students, and even more experienced scientists, this 'in-house' script is a mystery that is conceptually out of reach. However, I believe that there is a false dichotomy of 'knowing programming' or 'not knowing programming' that is prevalent in chemistry, and wet-lab science in general. While understanding very basic coding principles like variables, loops, and functions may be prerequisite information, well-written code can be implemented by almost anyone who is familiar with the underlying scientific principles. In all peer-reviewed journals, these 'in-house' scripts should be published as supporting information, or available on a platform like git-hub. With only a small amount of experience with code and a good search engine, any researcher should be able to take these available resources and apply them to their own questions and data. The goal of this tutorial is to show students that they can take code and use it to answer questions that have real scientific applications, which is an invaluable skill in a research career. 
